apiVersion: v1
kind: Service
metadata:
    name: "memsql-7bdc"
    labels:
        app: "memsql-7bdc"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "memsql-7bdc"